student:
  default:
    age: 20
    firstName: Test
    lastName: TestTest
    enabled: true

spring:
  main:
    allow-bean-definition-overriding: true
    
shell:
  interactive:
    enabled: false

